"""Report which LiveKit Agents plugins have a price in this catalog, and which do not.

Being a LiveKit plugin does not mean the vendor publishes a per-unit rate, so "how many plugins
are there" is not the same question as "how many can we price". This module answers the second
one and, just as importantly, says *why* each gap is a gap.

Two inputs, joined at build time:

- ``prices/sources/livekit_plugins.json``: the plugin registry. Committed, hand-maintained, and
  the only place a classification or a skip reason lives. Refresh the package list against GitHub
  with ``REFRESH=1 make livekit-coverage``; new packages arrive as ``not_investigated`` and
  existing notes are never overwritten.
- ``prices/data.json``: the built catalog. Whether a plugin counts as covered is *derived* from
  it, never recorded in the registry, so the two can never disagree.

Coverage is counted per *slot*, not per plugin: a slot is one (plugin, modality) pair, taken
from the classes the plugin package actually exports. This matters because a vendor can be in the
catalog for the wrong thing. `livekit-plugins-azure` is Azure Speech (STT and TTS), and pricing
Azure's LLMs does nothing for it. Counting by plugin would call that covered; counting by slot
calls it what it is.

An entry whose ``provider_id`` does not resolve to a provider in the catalog is an error rather
than a silent miss: that is what a provider rename looks like.

Output is ``docs/livekit-coverage.mdx``, regenerated by ``make build`` along with every other
generated page.
"""

from __future__ import annotations

import json
import os
import urllib.request
from datetime import date
from pathlib import Path
from typing import Any, Literal, NamedTuple, cast

from .utils import package_dir, root_dir

REGISTRY = package_dir / 'sources' / 'livekit_plugins.json'
DATA_JSON = package_dir / 'data.json'
COVERAGE_PAGE = root_dir / 'docs' / 'livekit-coverage.mdx'

CONTENTS_API = 'https://api.github.com/repos/livekit/agents/contents/livekit-plugins'
PLUGINS_URL = 'https://github.com/livekit/agents/tree/main/livekit-plugins'
CONTRIBUTE_URL = 'https://github.com/mahimailabs/voice-prices/blob/main/CONTRIBUTING.md'

Kind = Literal['inference', 'avatar', 'local', 'tooling', 'unknown']

#: Why a plugin that is not covered is not covered. ``not_investigated`` is deliberately its own
#: status: "nobody has looked yet" is a different claim from "we looked and there is no rate", and
#: collapsing the two would make the page overstate what has been checked.
#: ``non_usd_currency`` is likewise its own status rather than a flavour of ``no_public_rate``.
#: A vendor that publishes a clear per-unit rate in INR or CNY has not failed to publish
#: anything; this catalog is USD-only and does not convert (see docs/contribute.mdx), so the
#: gap is ours, not theirs. Saying "no public rate" about Sarvam would simply be false.
STATUS_LABEL: dict[str, str] = {
    'not_investigated': 'Not investigated yet',
    'no_public_rate': 'No public per-unit rate',
    'unpriceable_unit': 'Bills in a unit this schema has no field for',
    'non_usd_currency': 'Publishes rates, but not in USD',
}

#: Kinds that are outside what a *voice price* catalog can express, with the reason shown on the
#: page. Excluding them from the denominator is a judgement call, so it is stated, not hidden.
OUT_OF_SCOPE: dict[str, str] = {
    'avatar': 'Video avatar rendering. This catalog prices speech, and has no field that fits a rendered video minute.',
    'local': 'Runs inside the agent process or on your own hardware. There is no per-unit vendor bill to publish.',
    'tooling': 'Not inference: monitoring, or bundled into the platform bill rather than metered per unit.',
}

KIND_ORDER: tuple[Kind, ...] = ('inference', 'avatar', 'local', 'tooling', 'unknown')


#: Modalities a LiveKit plugin can expose, read from the classes its package exports (`STT`,
#: `TTS`, `LLM`, `RealtimeModel`). `realtime` is one plugin capability but two catalog tabs: a
#: realtime vendor is priced either per audio token (s2s) or per bundled minute (agent).
CAPABILITY_TABS: dict[str, tuple[str, ...]] = {
    'stt': ('stt',),
    'tts': ('tts',),
    'llm': ('llm',),
    'realtime': ('s2s', 'agent'),
}

CAPABILITY_LABEL: dict[str, str] = {'stt': 'STT', 'tts': 'TTS', 'llm': 'LLM', 'realtime': 'Realtime'}


class Plugin(NamedTuple):
    package: str
    vendor: str
    kind: Kind
    provides: tuple[str, ...]
    provider_id: str | None
    status: str | None
    note: str | None


class Coverage(NamedTuple):
    """One plugin joined against the catalog, slot by slot."""

    plugin: Plugin
    modalities: tuple[str, ...]
    """Catalog tabs the vendor appears under, whether or not this plugin uses them."""
    model_count: int
    priced: tuple[str, ...]
    """Capabilities this plugin provides that the catalog prices."""
    unpriced: tuple[str, ...]
    """Capabilities this plugin provides that the catalog does not price."""

    @property
    def state(self) -> Literal['full', 'partial', 'none']:
        if not self.priced:
            return 'none'
        return 'full' if not self.unpriced else 'partial'


def load_registry(path: Path | None = None) -> tuple[dict[str, Any], list[Plugin]]:
    raw = cast('dict[str, Any]', json.loads((path or REGISTRY).read_text()))
    plugins = [
        Plugin(
            package=str(entry['package']),
            vendor=str(entry['vendor']),
            kind=cast('Kind', entry.get('kind', 'unknown')),
            provides=tuple(cast('list[str]', entry.get('provides', []))),
            provider_id=cast('str | None', entry.get('provider_id')),
            status=cast('str | None', entry.get('status')),
            note=cast('str | None', entry.get('note')),
        )
        for entry in cast('list[dict[str, Any]]', raw['plugins'])
    ]
    return raw, plugins


def _catalog_index(data: list[dict[str, Any]]) -> dict[str, tuple[tuple[str, ...], int]]:
    """Map provider id to the modalities it prices and how many models that is.

    Built with ``build_docs.build_catalog`` rather than a second reading of the price fields, so
    this page and the docs tabs can never classify the same model differently.
    """
    # Imported here rather than at module scope: build_docs calls back into this module to render
    # the page, so a top-level import would be circular.
    from .build_docs import CATEGORIES, build_catalog

    catalog = build_catalog(data)
    index: dict[str, tuple[tuple[str, ...], int]] = {}
    for category in CATEGORIES:
        for entry in catalog[category]:
            modalities, count = index.get(entry['id'], ((), 0))
            index[entry['id']] = ((*modalities, category), count + len(entry['models']))
    return index


def build_coverage(plugins: list[Plugin], data: list[dict[str, Any]]) -> list[Coverage]:
    """Join the registry against the catalog, raising if a registry entry points at nothing."""
    index = _catalog_index(data)
    known = {str(provider.get('id', '')) for provider in data}

    unresolved = [p.package for p in plugins if p.provider_id is not None and p.provider_id not in known]
    if unresolved:
        raise ValueError(
            f'{len(unresolved)} plugin(s) in {REGISTRY.name} name a provider that is not in the catalog: '
            f'{unresolved}. A provider was probably renamed; update `provider_id` in the registry.'
        )

    coverage: list[Coverage] = []
    for plugin in plugins:
        modalities, count = index.get(plugin.provider_id or '', ((), 0))
        priced = tuple(c for c in plugin.provides if set(CAPABILITY_TABS[c]) & set(modalities))
        unpriced = tuple(c for c in plugin.provides if c not in priced)
        coverage.append(
            Coverage(
                plugin=plugin,
                modalities=modalities,
                model_count=count,
                priced=priced,
                unpriced=unpriced,
            )
        )
    return coverage


# --- refresh -----------------------------------------------------------------


def _fetch_packages() -> list[str]:
    request = urllib.request.Request(CONTENTS_API, headers={'Accept': 'application/vnd.github+json'})
    with urllib.request.urlopen(request, timeout=30) as response:
        entries = cast('list[dict[str, Any]]', json.loads(response.read()))
    return sorted(str(entry['name']) for entry in entries if entry.get('type') == 'dir')


def refresh_registry(path: Path | None = None) -> tuple[list[str], list[str]]:
    """Sync the registry's package list with the live repository.

    Additions land as ``kind: unknown`` / ``status: not_investigated`` so a new plugin shows up on
    the page as an open gap instead of being silently absent. Removals are reported but not
    deleted: a package that disappears upstream may just have been renamed, and the note attached
    to it is worth a human glance before it is thrown away.
    """
    path = path or REGISTRY
    raw, plugins = load_registry(path)
    live = _fetch_packages()
    have = {plugin.package for plugin in plugins}

    added = [package for package in live if package not in have]
    removed = sorted(have - set(live))

    entries = cast('list[dict[str, Any]]', raw['plugins'])
    entries += [
        {'package': package, 'vendor': package, 'kind': 'unknown', 'status': 'not_investigated'} for package in added
    ]
    entries.sort(key=lambda entry: str(entry['package']))
    raw['checked'] = date.today().isoformat()
    path.write_text(json.dumps(raw, indent=2) + '\n')
    return added, removed


# --- rendering ---------------------------------------------------------------


def _cell(text: str) -> str:
    return text.replace('|', '\\|')


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return '_None._'
    lines = ['| ' + ' | '.join(headers) + ' |', '| ' + ' | '.join('---' for _ in headers) + ' |']
    lines += ['| ' + ' | '.join(row) + ' |' for row in rows]
    return '\n'.join(lines)


def _links_for(coverage: Coverage, capabilities: tuple[str, ...]) -> str:
    """Link each priced capability to the docs tab that actually carries its rate."""
    from .build_docs import slug

    provider = slug(coverage.plugin.provider_id or '')
    out: list[str] = []
    for capability in capabilities:
        tab = next((t for t in CAPABILITY_TABS[capability] if t in coverage.modalities), None)
        if tab is None:
            out.append(CAPABILITY_LABEL[capability])
        else:
            out.append(f'[{CAPABILITY_LABEL[capability]}](/{tab}/{provider})')
    return ', '.join(out)


def _labels(capabilities: tuple[str, ...]) -> str:
    return ', '.join(CAPABILITY_LABEL[c] for c in capabilities) or 'not recorded'


def _why_not(coverage: Coverage) -> str:
    """The reason a slot is empty, preferring a recorded one over the default."""
    plugin = coverage.plugin
    if plugin.note:
        return f'{STATUS_LABEL.get(plugin.status or "", "").rstrip(".")}. {plugin.note}'.lstrip('. ')
    # The vendor is in the catalog, just not for anything this plugin does. That is a more
    # specific (and more actionable) answer than "not investigated", so say it instead. Only for
    # a wholly unpriced plugin: on a partly priced one it would repeat the modalities the row
    # already lists as priced, and read as if they were the problem.
    if coverage.state == 'none' and plugin.provider_id and coverage.modalities:
        from .build_docs import CATEGORY_META

        priced_for = ', '.join(CATEGORY_META[cast('Any', m)].tab for m in coverage.modalities)
        return f'Priced here for {priced_for} only, which is not what this plugin calls.'
    return STATUS_LABEL.get(plugin.status or 'not_investigated', 'Unknown') + '.'


def _by_vendor(coverage: Coverage) -> str:
    return coverage.plugin.vendor.lower()


def render_coverage_page(coverage: list[Coverage], checked: str) -> str:
    # One disclaimer for the whole site, defined next to the pages that show rates.
    from .build_docs import PRICE_DISCLAIMER

    inference = [c for c in coverage if c.plugin.kind in ('inference', 'unknown')]
    full = [c for c in inference if c.state == 'full']
    partial = [c for c in inference if c.state == 'partial']
    none = [c for c in inference if c.state == 'none']

    pct = round(100 * len(full) / len(inference)) if inference else 0

    by_status: dict[str, int] = {}
    for c in none:
        key = c.plugin.status or 'not_investigated'
        by_status[key] = by_status.get(key, 0) + 1
    breakdown = ', '.join(
        f'{count} {STATUS_LABEL[status].lower()}'
        for status, count in sorted(by_status.items())
        if status in STATUS_LABEL
    )

    out_of_scope = [c for c in coverage if c.plugin.kind in OUT_OF_SCOPE]

    parts = [
        '---',
        'title: "LiveKit plugin coverage"',
        'description: "Which LiveKit Agents plugins have a price in this catalog, and why the rest do not."',
        '---',
        '',
        f'LiveKit Agents ships **{len(coverage)} plugin packages**. **{len(inference)}** of them call a '
        f'metered inference vendor. Of those, this catalog prices **{len(full)} fully** '
        f'(**{pct}%**), **{len(partial)} partly**, and **{len(none)} not at all**.',
        '',
        '"Fully" is measured against what the plugin itself calls, not against the vendor name. A '
        'vendor can be in this catalog for the wrong thing: `livekit-plugins-azure` is Azure '
        'Speech, so an Azure LLM price does nothing for it, and that plugin counts as unpriced. '
        'The Priced and Missing columns below show the split per plugin.',
        '',
        'The gaps are the useful half of this page, and most are not gaps in effort. A vendor that '
        'sells credit bundles without publishing a credits-per-character ratio cannot be put in a '
        'per-unit catalog at all, however long you look at its pricing page.',
        '',
        f'Plugin list and capabilities read from [livekit/agents]({PLUGINS_URL}) on {checked}.',
        '',
        'Coverage here says a rate exists, not that it is right.',
        '',
        PRICE_DISCLAIMER,
        '',
        '## Fully priced',
        '',
        f'{len(full)} plugins where every modality the plugin exposes has a rate here. Follow a link '
        'for the rates, the source URL, and when a human last confirmed them.',
        '',
        _table(
            ['Plugin', 'Vendor', 'Priced for', 'Models'],
            [
                [f'`{_cell(c.plugin.package)}`', _cell(c.plugin.vendor), _links_for(c, c.priced), str(c.model_count)]
                for c in sorted(full, key=_by_vendor)
            ],
        ),
        '',
        '## Partly priced',
        '',
        f'{len(partial)} plugins where some of what the plugin does has a rate and some does not. '
        'These are the ones most likely to be misread as covered.',
        '',
        _table(
            ['Plugin', 'Vendor', 'Priced', 'Missing', 'Why'],
            [
                [
                    f'`{_cell(c.plugin.package)}`',
                    _cell(c.plugin.vendor),
                    _links_for(c, c.priced),
                    _labels(c.unpriced),
                    _cell(_why_not(c)),
                ]
                for c in sorted(partial, key=_by_vendor)
            ],
        ),
        '',
        '## Not priced',
        '',
        f'{len(none)} plugins with no rate here for anything they do'
        + (f': {breakdown}.' if breakdown else '.')
        + ' "Not investigated yet" means exactly that: nobody has checked whether the vendor '
        'publishes a rate. Those are the tractable ones, and a '
        f'[pull request]({CONTRIBUTE_URL}) closing any of them is welcome.',
        '',
        _table(
            ['Plugin', 'Vendor', 'Plugin does', 'Why not'],
            [
                [
                    f'`{_cell(c.plugin.package)}`',
                    _cell(c.plugin.vendor),
                    _labels(c.plugin.provides),
                    _cell(_why_not(c)),
                ]
                for c in sorted(none, key=lambda c: (c.plugin.status or '', c.plugin.vendor.lower()))
            ],
        ),
        '',
        '## Out of scope',
        '',
        f'{len(out_of_scope)} plugins are excluded from the counts above rather than counted as '
        'misses. They are listed so the denominator is checkable:',
        '',
    ]

    for kind in ('avatar', 'local', 'tooling'):
        members = [c for c in out_of_scope if c.plugin.kind == kind]
        if not members:
            continue
        parts += [
            f'**{kind.title()} ({len(members)}).** {OUT_OF_SCOPE[kind]}',
            '',
            ', '.join(f'`{_cell(c.plugin.package)}`' for c in sorted(members, key=lambda c: c.plugin.package)),
            '',
        ]

    parts += [
        '## How this page is made',
        '',
        'Generated by `make livekit-coverage` (and by `make build`, so it cannot drift) from two '
        'files: the plugin registry at `prices/sources/livekit_plugins.json`, which holds each '
        "plugin's capabilities, its classification and any skip reason, and `prices/data.json`, "
        'which holds the prices. Whether a slot counts as priced is derived from the catalog at '
        'build time and is never written down in the registry, so the two cannot disagree.',
        '',
        '`REFRESH=1 make livekit-coverage` re-reads the package list from GitHub. A plugin that '
        'appeared upstream since the last refresh is added as not investigated, which is how a new '
        'vendor becomes visible here instead of quietly widening the gap.',
        '',
    ]
    return '\n'.join(parts)


def write_coverage_page(data: list[dict[str, Any]], page: Path | None = None) -> tuple[bool, list[Coverage]]:
    """Regenerate the coverage page. Returns whether it changed, and the joined rows."""
    from .build_docs import write_if_changed

    raw, plugins = load_registry()
    coverage = build_coverage(plugins, data)
    content = render_coverage_page(coverage, str(raw.get('checked', 'an unrecorded date')))
    return write_if_changed(page or COVERAGE_PAGE, content), coverage


def livekit_coverage() -> int:
    """Report which LiveKit plugins have a price here (REFRESH=1 to re-read the plugin list)."""
    if os.getenv('REFRESH'):
        added, removed = refresh_registry()
        for package in added:
            print(f'new plugin upstream: {package} (added as not investigated)')
        for package in removed:
            print(f'WARNING: {package} is in the registry but no longer upstream; renamed or dropped?')
        if not added and not removed:
            print('plugin list already matches upstream')

    data = cast('list[dict[str, Any]]', json.loads(DATA_JSON.read_text()))
    changed, coverage = write_coverage_page(data)

    counts = {kind: sum(1 for c in coverage if c.plugin.kind == kind) for kind in KIND_ORDER}
    inference = [c for c in coverage if c.plugin.kind in ('inference', 'unknown')]
    states = {state: sum(1 for c in inference if c.state == state) for state in ('full', 'partial', 'none')}
    pct = round(100 * states['full'] / len(inference)) if inference else 0

    print(f'{len(coverage)} LiveKit plugins: ' + ', '.join(f'{n} {k}' for k, n in counts.items() if n))
    print(f'plugin coverage: {states["full"]}/{len(inference)} fully priced ({pct}%)')
    print(f'  {states["partial"]} partly priced, {states["none"]} not priced at all')
    for status in sorted(STATUS_LABEL):
        n = sum(1 for c in inference if c.state == 'none' and (c.plugin.status or 'not_investigated') == status)
        if n:
            print(f'  {n} {STATUS_LABEL[status].lower()}')
    print(f'{COVERAGE_PAGE.relative_to(root_dir)} {"updated" if changed else "unchanged"}')
    return 0


def main() -> None:
    raise SystemExit(livekit_coverage())


if __name__ == '__main__':
    main()
